# Generated by Django 2.2.4 on 2020-02-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20200210_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='added_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
